### ISSUE TITLE
Unclosed cursor

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/com.aware.plugin.google.fused_location#3]
I found the following exception with the latest version of this plugin:

```
E/Cursor: Finalizing a Cursor that has not been deactivated or closed. database = /storage/emulated/0/AWARE/fused_geofences.db, table = fused_geofences, query = SELECT double_longitude, timestamp, double_radius, geofence_label, device_id, _id, double_latitude F
                                           net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                               at net.sqlcipher.database.SQLiteCursor.<init>(SQLiteCursor.java:217)
                                               at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:53)
                                               at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1772)
                                               at net.sqlcipher.database.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:330)
                                               at net.sqlcipher.database.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:280)
                                               at com.aware.plugin.google.fused_location.Provider.query(Provider.java:172)
                                               at android.content.ContentProvider.query(ContentProvider.java:1000)
                                               at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
                                               at android.content.ContentResolver.query(ContentResolver.java:482)
                                               at android.content.ContentResolver.query(ContentResolver.java:426)
```

**Comment by denzilferreira** [comment]
Thanks! Any hints on what you did in terms of interface interaction to cause this error?

**Comment by JulioV** [comment]
Just installed it, open "Streams", took a look at the widget there, opened the plugin's settings and that was it.

**Comment by denzilferreira** [comment]
Should be OK now.
